name: base
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - archspec=0.2.5=pyhd8ed1ab_0
  - boltons=25.0.0=pyhd8ed1ab_0
  - brotli-python=1.1.0=py312h6b01ec3_4
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py312h1b4d9a2_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - conda=25.9.1=py312h81bd7bf_0
  - conda-libmamba-solver=25.4.0=pyhd8ed1ab_0
  - conda-package-handling=2.4.0=pyh7900ff3_2
  - conda-package-streaming=0.12.0=pyhd8ed1ab_0
  - cpp-expected=1.3.1=h4f10f1e_0
  - cpython=3.12.12=py312hd8ed1ab_1
  - distro=1.9.0=pyhd8ed1ab_1
  - filelock=3.20.0=pyhd8ed1ab_0
  - fmt=12.0.0=h669d743_0
  - frozendict=2.4.6=py312h163523d_1
  - giflib=5.2.2=h93a5062_0
  - gmp=6.3.0=h7bae524_2
  - gmpy2=2.2.1=py312hee6aa52_2
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.11=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jsonpatch=1.33=pyhd8ed1ab_1
  - jsonpointer=3.0.0=py312h81bd7bf_2
  - krb5=1.21.3=h237132a_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libarchive=3.8.2=gpl_h46575ef_100
  - libblas=3.11.0=1_h51639a9_openblas
  - libcblas=3.11.0=1_hb0561ab_openblas
  - libcurl=8.16.0=hdece5d2_0
  - libcxx=21.1.4=hf598326_0
  - libdeflate=1.25=hc11a715_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - libiconv=1.18=h23cfdf5_2
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.11.0=1_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libmamba=2.3.3=h1370271_2
  - libmambapy=2.3.3=py312haad32af_2
  - libnghttp2=1.67.0=hc438710_0
  - libopenblas=0.3.30=pthreads_h735b822_4
  - libpng=1.6.50=h280e0eb_1
  - libsolv=0.7.35=h5f525b2_0
  - libsqlite=3.50.4=h4237e3c_0
  - libssh2=1.11.1=h1590b86_0
  - libtiff=4.7.1=h4030677_1
  - libwebp=1.6.0=hc0253d1_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.15.1=h9329255_0
  - libxml2-16=2.15.1=h0ff4647_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=15.0.7=h7cfbb63_0
  - lz4-c=1.10.0=h286801f_1
  - lzo=2.10=h925e9cb_1002
  - mamba=2.3.3=hb90242b_2
  - markupsafe=3.0.3=py312h5748b74_0
  - menuinst=2.4.1=py312h81bd7bf_0
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - networkx=3.5=pyhe01879c_0
  - nlohmann_json-abi=3.12.0=h0f90c79_1
  - numpy=2.3.5=py312h85ea64e_0
  - openjpeg=2.5.4=hbfb3c88_0
  - openssl=3.6.0=h5503f6c_0
  - packaging=25.0=pyh29332c3_1
  - pillow=12.0.0=py312h16e1670_0
  - pip=25.2=pyh8b19718_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - pluggy=1.6.0=pyhd8ed1ab_0
  - pthread-stubs=0.4=hd74edd7_1002
  - pybind11-abi=11=hc364b38_1
  - pycosat=0.6.6=py312h163523d_3
  - pycparser=2.22=pyh29332c3_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.12=h18782d2_1_cpython
  - python_abi=3.12=8_cp312
  - pytorch=2.5.1=py3.12_0
  - pyyaml=6.0.3=py312h5748b74_0
  - readline=8.2=h1d1bf99_2
  - reproc=14.2.5.post0=h5505292_0
  - reproc-cpp=14.2.5.post0=h286801f_0
  - requests=2.32.5=pyhd8ed1ab_0
  - ruamel.yaml=0.18.16=py312h4409184_0
  - ruamel.yaml.clib=0.2.14=py312h4409184_0
  - setuptools=80.9.0=pyhff2d567_0
  - simdjson=4.0.7=ha7d2532_0
  - tk=8.6.13=h892fb3f_2
  - torchaudio=2.5.1=py312_cpu
  - torchvision=0.20.1=py312_cpu
  - tqdm=4.67.1=pyhd8ed1ab_1
  - truststore=0.10.3=pyhe01879c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - yaml=0.2.5=h925e9cb_3
  - yaml-cpp=0.8.0=ha1acc90_0
  - zlib-ng=2.2.5=h3470cca_0
  - zstandard=0.25.0=py312h37e1c23_0
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - attrs==25.4.0
      - blinker==1.9.0
      - cattrs==25.3.0
      - click==8.3.1
      - coremltools==9.0
      - faiss-cpu==1.13.2
      - flask==3.1.2
      - flask-cors==6.0.1
      - frozenlist==1.8.0
      - fsspec==2026.1.0
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - iniconfig==2.3.0
      - itsdangerous==2.2.0
      - joblib==1.5.3
      - ml-dtypes==0.5.4
      - multidict==6.7.0
      - onnx==1.20.1
      - propcache==0.4.1
      - protobuf==6.33.4
      - psutil==7.2.1
      - pyaml==25.7.0
      - pygments==2.19.2
      - pyparsing==3.3.1
      - pytest==9.0.1
      - regex==2026.1.15
      - safetensors==0.7.0
      - scikit-learn==1.8.0
      - scipy==1.17.0
      - sentence-transformers==5.2.0
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - timm==1.0.24
      - tokenizers==0.22.2
      - torch-geometric==2.7.0
      - transformers==4.57.6
      - werkzeug==3.1.4
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /Users/nani/miniforge3
